### ISSUE TITLE
Fogstream ревью

### ISSUE THREAD

**Issue by nikvst** [ran1024/example#1]
1. каталога .idea не должно быть в репозитории, следует добавить его в gitignore

2. часть настроек рекомендуется задавать отдельно (через переменные окружения, json, yaml или ini файл), а в файле settings.py просто импортировать их из нужного источника. Это позволит не хранить в репозитории такие важные вещи как secret_key, пароли от почты, БД и т. п.

3. Имена коммитов должны отражать проделанные изменения

4. Отсутствуют тесты. Написанные тесты являлись частью тестового задания!

5. Авторизацию/регистрацию и отправку email следовало разнести на разные apps

6. https://github.com/ran1024/example/blob/master/myexample/webapp/views.py#L83
Следует обрабатывать исключения, могут вылететь сетевые ошибки 

7. https://github.com/ran1024/example/blob/master/myexample/webapp/views.py#L65
Администратора следует доставать по признаку, что он администратор, а не по имени пользователя.

8. Отсутствуют миграции

**Comment by ran1024** [comment]
Согласен.
